Workaround problem with concurrent .pdb access in Windows
With -j2, builds often encounter this error (only since recently...):

    platform\windows\crash_handler_windows.cpp: fatal error C1041:
    cannot open program database 'D:\a\godot4-nightly\godot4-nightly\vc140.pdb';
    if multiple CL.EXE write to the same .PDB file, please use /FS

If -j2 causes errors at the very end, we run again with -j1, which can reuse a lot of the compile progress.